## Q1. What do you mean by ensemble technique, explain the Random Forest algorithm?

Ensembleing means taking all base decesion tree values and making a appropriate model from it which is known as Random forest. In random forest algorithm we take different hyperparameters to make our model using various uncorrelated base models of decesion tree so that ourr model is more precise and accurate, plus it would be less overfit.  

## Q2. What do you understand by Bagging?

Bagging means each individaul tree taking randomly sample values from dataset with replacement, which result in different trees.

## Q3. What does random refer to in ‘Random Forest’?

Random refers to random models we take for making our model, random variables selected for splitting at each node

## Q4. How decision trees in Random Forest are different from decision tree in Decision Tree algorithm?

Decesion tree algorithm refers to the model we make using decision tree classifier, since we are using one tree to predict accuracy of our model it works fast, but is mostly overfitted. Whereas in Random Forest we take various decesion trees with different values, due to ensemble of decesion trees it becomes slow for training and testing of data, but gives better accuracy than decesion trees and is less over fitted

## Q5. What are overfitting and underfitting? Why does the decision tree algorithm suffer often with overfitting problems?

Overfitting means model as high variance which inturn means that a slight change in hyperparameters or training data will give high varied output, where as underfitting means we have high bias which means we are making big assumptions for the data. Since decesion trees is designed so as to perfectly fit all samples in the training data set. Thus it ends up with branches with strict rules of sparse data. so this effects the accuracy when predicting samples that are not part of the training set.

## Q6. Name a few hyper-parameters of decision trees?

Hyperparameters:criterion,splitter,max_depth,min_samples_split,min_samples_leaf,min_weight_fraction_leaf
,max_features,random_state,max_leaf_nodes,min_impurity_decrease,class_weight,ccp_alpha

## Q7. What is bagging and feature randomness in Random Forest Classifier.

Bagging - Bagging means each individaul tree taking randomly sample values from dataset with replacement, which result in different trees.
Feature andomness - in this we take two or required features together within which we take random sample values with replacement which result in lower correlation of trees and more diversification

## Q8. Given a dataset of children who had kyphosis(a spinal condition) and they underwent an operation. The dataset has the following columns:Kyphosis: whether or not the kyphosis was present after operation.Age: age of children in months Number: number of vertebrae involved in the operation Start: the topmost vertebrae number involved in the operation

In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [7]:
data = pd.read_csv('Assignment -13 dataset.csv')

In [8]:
data

Kyphosis  Age  Number  Start
0    absent   71       3      5
1    absent  158       3     14
2   present  128       4      5
3    absent    2       5      1
4    absent    1       4     15
..      ...  ...     ...    ...
76  present  157       3     13
77   absent   26       7     13
78   absent  120       2     13
79  present   42       7      6
80   absent   36       4     13

[81 rows x 4 columns]

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64 
 2   Number    81 non-null     int64 
 3   Start     81 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 2.7+ KB


In [10]:
data['Age'].unique()

array([ 71, 158, 128,   2,   1,  61,  37, 113,  59,  82, 148,  18, 168,
        78, 175,  80,  27,  22, 105,  96, 131,  15,   9,   8, 100,   4,
       151,  31, 125, 130, 112, 140,  93,  52,  20,  91,  73,  35, 143,
        97, 139, 136, 121, 177,  68,  72, 120,  51, 102, 114,  81, 118,
        17, 195, 159, 127,  87, 206,  11, 178, 157,  26,  42,  36],
      dtype=int64)

In [11]:
data['Number'].unique()

array([ 3,  4,  5,  2,  6,  7,  9, 10], dtype=int64)

In [12]:
data['Start'].unique()

array([ 5, 14,  1, 15, 16, 17, 12,  2, 18, 13,  9,  3,  6, 11, 10,  8],
      dtype=int64)

In [13]:
data['Kyphosis'].value_counts()

absent     64
present    17
Name: Kyphosis, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
data['Kyphosis'] = le.fit_transform(data['Kyphosis'])

In [17]:
data['Kyphosis'].value_counts()

0    64
1    17
Name: Kyphosis, dtype: int64

In [18]:
data

Kyphosis  Age  Number  Start
0          0   71       3      5
1          0  158       3     14
2          1  128       4      5
3          0    2       5      1
4          0    1       4     15
..       ...  ...     ...    ...
76         1  157       3     13
77         0   26       7     13
78         0  120       2     13
79         1   42       7      6
80         0   36       4     13

[81 rows x 4 columns]

In [27]:
x = data.drop('Kyphosis', axis = 1).values
y = data['Kyphosis']

In [30]:
from sklearn.model_selection import train_test_split

In [43]:
x1_train,x1_test,y1_train,y1_test =train_test_split(x,y, test_size = .3, random_state = 30)

In [44]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [45]:
x1_train = ss.fit_transform(x1_train)

In [46]:
x1_test = ss.transform(x1_test)

In [47]:
from sklearn.tree import DecisionTreeClassifier
dc = DecisionTreeClassifier()

In [48]:
dc.fit(x1_train,y1_train)

DecisionTreeClassifier()

In [49]:
y1_pred = dc.predict(x1_test)

In [50]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y1_test, y1_pred)

array([[17,  2],
       [ 2,  4]], dtype=int64)

In [51]:
## for testing data
from sklearn.metrics import classification_report
print(classification_report(y1_test, y1_pred))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        19
           1       0.67      0.67      0.67         6

    accuracy                           0.84        25
   macro avg       0.78      0.78      0.78        25
weighted avg       0.84      0.84      0.84        25



In [52]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y1_test,y1_pred)

array([[17,  2],
       [ 2,  4]], dtype=int64)